FROM alpine:3.23
ARG REPO="https://github.com/clementdlg/dotfiles.git"
ARG USER="krem"
ARG HOME="/home/$USER"
ARG XDG_CONFIG_HOME="${HOME}/.config"

# install dependencies
RUN apk add --no-cache just curl bash
RUN adduser -h "$HOME" -D "$USER"

# add dotfiles
ADD $REPO "$HOME/.config"
WORKDIR "$XDG_CONFIG_HOME"

# install nix
RUN just nix && \
	chown -R "$USER": "$HOME" && \
	chown -R "$USER": /nix

# setup user environement and install packages
USER $USER
RUN just home-manager
# RUN just nvim && just bashrc

ENV USER="$USER"
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENTRYPOINT ["/home/krem/.nix-profile/bin/tmux"]
